Add members to repository
vtanja/UKS pull request #75
Opened 2021-02-14 13:29 UTC by veca22

2021-02-14 14:21 UTC, nikolina-sarenac approved these changes

2021-02-14 15:50 UTC, balsa-sarenac requested changes

2021-02-14 15:50 UTC, balsa-sarenac commented on uks/apps/repository/views.py
> +# Bug brise iz baze celog usera
If this bug is still active probably the reason is cascade delete. Check on_delete property for attribute user

2021-02-14 15:50 UTC, balsa-sarenac commented on uks/apps/repository/views.py
> +def RepositorySettings(request, id):
We need login request here as well

2021-02-15 12:48 UTC, vtanja approved these changes

2021-02-15 15:31 UTC, balsa-sarenac approved these changes

2021-02-15 15:32 UTC, merged